name: Hello Workflow

on: [push]

jobs:
  hello-job:
    runs-on: self-hosted
    steps:
      - name: Print hello
        run: echo "Hello GH-200 prep!"
      - name: Print hello and save locally
        run: | 
            echo "Hello GH-200 prep!" | tee output.log

